[package]
name = "rust-solana-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = {version = "4.5.4", features = ["derive"]}
chrono = "0.4.38"
solana-client = "1.18.11"
solana-sdk = "1.18.11"
tiny-bip39 = "0.8.2"
